"""Shared status names for tasks and queue items."""

TASK_STATUS_PLANNED = "planned"
TASK_STATUS_CONTRACTED = "contracted"
TASK_STATUS_IN_PROGRESS = "in_progress"
TASK_STATUS_SENSORS_FAILED = "sensors_failed"
TASK_STATUS_SENSORS_PASSED = "sensors_passed"
TASK_STATUS_NEEDS_WORK = "needs_work"
TASK_STATUS_REVIEW_FOLLOWUP = "review_followup"
TASK_STATUS_PASSED = "passed"
TASK_STATUS_FAILED = "failed"
TASK_STATUS_DONE = "done"

QUEUE_STATUS_QUEUED = "queued"
QUEUE_STATUS_ACTIVE = "active"
QUEUE_STATUS_DONE = "done"
QUEUE_STATUS_SKIPPED = "skipped"
QUEUE_STATUS_BLOCKED = "blocked"

TASK_STATUSES_READY_TO_START = {TASK_STATUS_PLANNED, TASK_STATUS_CONTRACTED}
TASK_STATUSES_WORKING = {TASK_STATUS_IN_PROGRESS, TASK_STATUS_SENSORS_FAILED, TASK_STATUS_NEEDS_WORK}
TASK_STATUSES_COMPLETE = {TASK_STATUS_PASSED, TASK_STATUS_DONE}

